using System.Windows;

namespace HR_ERP.Helpers
{
    /// <summary>
    /// Minimal English/Arabic string table plus the app-wide language switch. Every screen
    /// added so far keeps its original English-only labels (translating all ten existing
    /// views is a much larger job than this feature); this covers the pieces that are
    /// language-aware today — the main nav, the login window, and the Settings screen
    /// itself — via <see cref="T"/>. Extending another screen to follow suit just means
    /// adding its strings to the two dictionaries below and swapping its XAML/code-behind
    /// text for <c>Localization.T("key")</c> calls, the same way MainWindow does.
    ///
    /// Switching languages also flips the whole window's <see cref="FlowDirection"/>
    /// (wired up in MainWindow) — that's what moves the left nav panel to the right side
    /// for Arabic and mirrors every grid/DataGrid column order along with it, which is the
    /// "if Arabic, right side view" requirement.
    /// </summary>
    public static class Localization
    {
        public static event Action? LanguageChanged;

        public static string CurrentLanguage { get; private set; } = "en";

        public static bool IsRightToLeft => CurrentLanguage == "ar";

        public static void SetLanguage(string languageCode)
        {
            CurrentLanguage = languageCode == "ar" ? "ar" : "en";
            LanguageChanged?.Invoke();
        }

        public static FlowDirection FlowDirection => IsRightToLeft ? FlowDirection.RightToLeft : FlowDirection.LeftToRight;

        /// <summary>Looks up a UI string by key in the current language, falling back to the
        /// key itself (not blowing up) if a translation is ever missing.</summary>
        public static string T(string key)
        {
            var table = IsRightToLeft ? Arabic : English;
            return table.TryGetValue(key, out var value) ? value : key;
        }

        private static readonly Dictionary<string, string> English = new()
        {
            // App / window
            ["AppTitle"] = "HR ERP",
            ["AppSubtitle"] = "Human Resources System",

            // Left nav
            ["Nav.Dashboard"] = "📊  Dashboard",
            ["Nav.Employees"] = "👤  Employees",
            ["Nav.Departments"] = "🏢  Departments & Positions",
            ["Nav.OrgStructure"] = "🌳  Org Structure",
            ["Nav.Shifts"] = "🕐  Shifts",
            ["Nav.Attendance"] = "🗓  Attendance",
            ["Nav.Leave"] = "✈  Leave & Holidays",
            ["Nav.Adjustments"] = "🎁  Bonuses & Penalties",
            ["Nav.CashAdvances"] = "💳  Cash Advances",
            ["Nav.Payroll"] = "💵  Payroll",
            ["Nav.Documents"] = "🗂  Documents",
            ["Nav.Settings"] = "⚙  Settings",
            ["Nav.SignOut"] = "🚪  Sign Out",

            // Login window
            ["Login.Title"] = "HR ERP — Sign In",
            ["Login.Username"] = "Username",
            ["Login.Password"] = "Password",
            ["Login.SignIn"] = "Sign In",
            ["Login.InvalidCredentials"] = "Invalid username or password, or this account is disabled.",
            ["Login.Required"] = "Enter both a username and password.",

            // Settings screen
            ["Settings.Title"] = "Settings",
            ["Settings.Tab.Users"] = "Users",
            ["Settings.Tab.Roles"] = "Roles & Permissions",
            ["Settings.Tab.Language"] = "Language",
            ["Settings.Users.Username"] = "Username",
            ["Settings.Users.FullName"] = "Full Name",
            ["Settings.Users.Employee"] = "Linked Employee (optional)",
            ["Settings.Users.Role"] = "Role",
            ["Settings.Users.Active"] = "Active",
            ["Settings.Users.Password"] = "Password",
            ["Settings.Users.New"] = "New",
            ["Settings.Users.Save"] = "Save",
            ["Settings.Users.Delete"] = "Delete",
            ["Settings.Users.ResetPassword"] = "Reset Password",
            ["Settings.Roles.Name"] = "Role Name",
            ["Settings.Roles.Description"] = "Description",
            ["Settings.Roles.Module"] = "Module",
            ["Settings.Roles.CanView"] = "Can View",
            ["Settings.Roles.CanEdit"] = "Can Add / Edit / Delete",
            ["Settings.Roles.New"] = "New",
            ["Settings.Roles.Save"] = "Save",
            ["Settings.Roles.Delete"] = "Delete",
            ["Settings.Roles.SavePermissions"] = "Save Permissions",
            ["Settings.Language.Prompt"] = "Choose the application language:",
            ["Settings.Language.English"] = "English",
            ["Settings.Language.Arabic"] = "العربية (Arabic)",
            ["Settings.Language.Apply"] = "Apply",
            ["Settings.Language.RestartNote"] = "Takes effect immediately — no restart needed.",
            // Attendance view
            ["Attendance.Header"] = "Attendance",
            ["Attendance.ImportExcel"] = "Import from Excel...",
            ["Attendance.Report.Button"] = "Print Report...",
            ["Attendance.Report.Title"] = "Attendance Report",
            ["Attendance.Report.TypeLabel"] = "Report Type",
            ["Attendance.Report.Type.Detailed"] = "Detailed Daily Log",
            ["Attendance.Report.Type.EmployeeSummary"] = "Monthly Summary (per employee)",
            ["Attendance.Report.Type.DepartmentSummary"] = "Department Summary",
            ["Attendance.Report.ScopeLabel"] = "Scope",
            ["Attendance.Report.Scope.All"] = "All Employees",
            ["Attendance.Report.Scope.Employee"] = "Single Employee:",
            ["Attendance.Report.Scope.Department"] = "Single Department:",
            ["Attendance.Report.DateRangeLabel"] = "Date Range",
            ["Attendance.Report.OutputLabel"] = "Output",
            ["Attendance.Report.Output.Print"] = "Print",
            ["Attendance.Report.Output.Excel"] = "Export to Excel",
            ["Attendance.Report.GenerateButton"] = "Generate",
            ["Attendance.Report.Validation.DateRange"] = "Pick a valid date range (end date on or after start date).",
            ["Attendance.Report.Validation.PickEmployee"] = "Pick an employee.",
            ["Attendance.Report.Validation.PickDepartment"] = "Pick a department.",
            ["Attendance.Report.Sent"] = "Report sent to the printer.",
            ["Attendance.Report.SaveExcelTitle"] = "Save Attendance Report",
            ["Attendance.Report.ExcelSaved"] = "Report saved.",
            ["Attendance.Report.Error"] = "Could not generate the report: {0}",
            ["Attendance.DownloadTemplate"] = "Download Template",
            ["Attendance.Mode.ByDay"] = "One day, all employees",
            ["Attendance.Mode.ByEmployee"] = "One employee, date range",
            ["Attendance.Filter.Date"] = "Date:",
            ["Attendance.Filter.Employee"] = "Employee:",
            ["Attendance.Filter.From"] = "From:",
            ["Attendance.Filter.To"] = "To:",
            ["Attendance.Button.ThisMonth"] = "This Month",
            ["Attendance.Column.Code"] = "Code",
            ["Attendance.Column.Employee"] = "Employee",
            ["Attendance.Column.Date"] = "Date",
            ["Attendance.Column.Day"] = "Day",
            ["Attendance.Column.Checkin"] = "Check-in",
            ["Attendance.Column.Checkout"] = "Check-out",
            ["Attendance.Column.Shift"] = "Shift",
            ["Attendance.Column.Late"] = "Late (min)",
            ["Attendance.Column.Early"] = "Early (min)",
            ["Attendance.Column.Overtime"] = "Overtime",
            ["Attendance.Column.TotalHrs"] = "Total Hrs",
            ["Attendance.Column.Status"] = "Status",
            ["Attendance.Column.Approved"] = "Approved",
            ["Attendance.Summary.PickEmployee"] = "Pick an employee and a date range to preview attendance.",
            ["Attendance.Edit.Header"] = "Add / Edit Attendance Record",
            ["Attendance.Edit.Employee"] = "Employee",
            ["Attendance.Edit.CheckinDate"] = "Check-in Date",
            ["Attendance.Edit.CheckinTime"] = "Check-in (HH:mm)",
            // Employees
            ["Employees.Header"] = "Employees",
            ["Employees.Search"] = "Search",
            ["Employees.Refresh"] = "Refresh",
            ["Employees.Filter.Department"] = "Department:",
            ["Employees.Filter.AllDepartments"] = "All Departments",
            ["Employees.SelectedBanner"] = "Editing: {0}  (Code: {1})",
            ["Employees.Documents.Header"] = "Personal Documents Hub",
            ["Employees.Documents.Hint"] = "Select an employee above to view or import their documents.",
            ["Employees.Documents.Description"] = "Secure per-employee document storage — National ID, Birth Certificate, Personal Photo, Graduation Certificate, Criminal Record (Fish), Military Status Certificate, Labor Office Card (Kaab Amal), Social Insurance Printout (Ta'meenat), Medical Fitness Certificate, and Contracts. Files are copied into the app's own EmployeeDocuments folder — never left pointing at the original location.",
            ["Employees.Documents.Column.Category"] = "Category",
            ["Employees.Documents.Column.FileName"] = "File Name",
            ["Employees.Documents.Column.Description"] = "Description",
            ["Employees.Documents.Column.Uploaded"] = "Uploaded",
            ["Employees.Documents.TypeTooltip"] = "Category for the next imported document",
            ["Employees.Documents.DescriptionTooltip"] = "Optional description for the next imported document",
            ["Employees.Documents.ImportButton"] = "\uD83D\uDCCE  Import Document...",
            ["Employees.Documents.ViewButton"] = "\uD83D\uDC41  View / Rename / Edit",
            ["Employees.Documents.DeleteButton"] = "Delete Selected",
            ["Employees.History.Header"] = "Employment History (Career Progression / Job History / Internal Mobility / Performance)",
            ["Employees.History.Hint"] = "Select an employee above to view their employment history.",
            ["Employees.History.Description"] = "Department Transfer / Position Change / Salary Change entries are logged automatically whenever you change and save those fields above. Performance Review and other entries are logged manually below.",
            ["Employees.History.Column.Date"] = "Date",
            ["Employees.History.Column.Event"] = "Event",
            ["Employees.History.Column.Change"] = "Change",
            ["Employees.History.Column.Notes"] = "Notes",
            ["Employees.History.Column.Recorded"] = "Recorded",
            ["Employees.History.EventType"] = "Event Type",
            ["Employees.History.EventDate"] = "Event Date",
            ["Employees.History.Notes"] = "Notes",
            ["Employees.History.Performance"] = "Performance Rating (if applicable)",
            ["Employees.History.Rating.Excellent"] = "Excellent",
            ["Employees.History.Rating.Good"] = "Good",
            ["Employees.History.Rating.Average"] = "Average",
            ["Employees.History.Rating.NeedsImprovement"] = "Needs Improvement",
            ["Employees.History.AddButton"] = "Add Manual Entry",
            ["Employees.History.DeleteButton"] = "Delete Selected",

            // Salary Details expander
            ["Employees.Salary.Header"] = "Salary Details",
            ["Employees.Salary.Hint"] = "Select an employee above to view or edit their salary details.",
            ["Employees.Salary.EntitlementsHeader"] = "Entitlements",
            ["Employees.Salary.Basic"] = "Basic Salary",
            ["Employees.Salary.FixedAllowance"] = "Fixed Allowances",
            ["Employees.Salary.Completion"] = "Salary Completion",
            ["Employees.Salary.OtherEntitlements"] = "Other Entitlements",
            ["Employees.Salary.DeductionsHeader"] = "Deductions",
            ["Employees.Salary.InsuranceAmount"] = "Social Insurance",
            ["Employees.Salary.MonthlyTax"] = "Monthly Tax",
            ["Employees.Salary.InsuranceNote"] = "Social Insurance is only deducted in Payroll while Insurance Status (above, in Add/Edit Employee) is set to Insured.",
            ["Employees.Salary.RatesHeader"] = "Additional Rates",
            ["Employees.Salary.OvertimeRate"] = "Overtime Rate (per hour)",
            ["Employees.Salary.LateDeductionRate"] = "Late Deduction Rate (per hour)",
            ["Employees.Salary.SaveButton"] = "Save Salary Details",
            ["Employees.Salary.HistoryHeader"] = "Salary Change History",
            ["Employees.Salary.History.Date"] = "Date",
            ["Employees.Salary.History.Insured"] = "Insured",
            ["Employees.Salary.History.ChangedBy"] = "Changed By",
            ["Employees.Dialog.SelectDocumentTitle"] = "Select document to import",
            ["Employees.Dialog.Filter.DocumentFiles"] = "All Files (*.*)|*.*|PDF (*.pdf)|*.pdf|Images (*.jpg;*.jpeg;*.png)|*.jpg;*.jpeg;*.png|Word Documents (*.doc;*.docx)|*.doc;*.docx",
            ["Employees.Info.SelectEmployeeFirst"] = "Select an employee first.",
            ["Employees.Info.SelectDocumentFirst"] = "Select a document first.",
            ["Employees.Error.CouldNotLoadDocuments"] = "Could not load documents: {0}",
            ["Employees.Error.ImportFailed"] = "Import failed: {0}",
            ["Employees.Error.CouldNotOpenDocument"] = "Could not open document: {0}",
            ["Employees.Confirm.DeleteDocument"] = "Delete '{0}'? This also removes the stored copy from disk.",
            ["Employees.Error.DeleteDocumentFailed"] = "Delete failed: {0}",
            ["Employees.Column.Code"] = "Code",
            ["Employees.Column.Name"] = "Name",
            ["Employees.Column.Department"] = "Department",
            ["Employees.Column.Position"] = "Position",
            ["Employees.Column.Email"] = "Email",
            ["Employees.Column.Phone"] = "Phone",
            ["Employees.Column.HireDate"] = "Hire Date",
            ["Employees.Column.Status"] = "Status",
            ["Employees.Edit.Header"] = "Add / Edit Employee",
            ["Employees.Edit.EmployeeCode"] = "Employee Code",
            ["Employees.Edit.FullName"] = "Full Name",
            ["Employees.Edit.Gender"] = "Gender",
            ["Employees.Edit.Dob"] = "Date of Birth",
            ["Employees.Edit.Email"] = "Email",
            ["Employees.Edit.Phone"] = "Phone",
            ["Employees.Edit.HireDate"] = "Hire Date",
            ["Employees.Edit.NationalId"] = "National ID",
            ["Employees.Edit.Department"] = "Department",
            ["Employees.Edit.Position"] = "Position",
            ["Employees.Edit.EmploymentType"] = "Employment Type",
            ["Employees.Edit.EmploymentStatus"] = "Employment Status",
            ["Employees.Edit.Address"] = "Address",
            ["Employees.Edit.Weekend1"] = "Weekend Day 1",
            ["Employees.Edit.Weekend2"] = "Weekend Day 2",
            ["Employees.Edit.MaritalStatus"] = "Marital Status",
            ["Employees.Edit.BasicSalary"] = "Basic Salary",
            ["Employees.Edit.Allowance"] = "Allowance",
            ["Employees.Edit.OvertimeRate"] = "Overtime Rate (per hour)",
            ["Employees.Edit.LateDeductionRate"] = "Late Deduction Rate (per hour)",
            ["Employees.Edit.AnnualLeaveDays"] = "Annual Leave Days/Year",
            ["Employees.Edit.LeaveCarriedOver"] = "Leave Carried Over (days)",
            ["Employees.Edit.ReportsTo"] = "Reports To (for Org Chart)",
            ["Employees.Edit.InsuranceStatus"] = "Insurance Status",
            ["Employees.Button.New"] = "New",
            ["Employees.Button.Edit"] = "Edit",
            ["Employees.Button.Save"] = "Save",
            ["Employees.Button.Delete"] = "Delete",
            ["Employees.Detail.WindowTitle"] = "Employee",
            ["Employees.Detail.MainDataHeader"] = "Employee",
            ["Employees.Detail.Tab.Details"] = "Details",
            ["Employees.Detail.Tab.Documents"] = "Documents",
            ["Employees.Detail.Tab.History"] = "History",
            ["Employees.Detail.Tab.Salary"] = "Salary",
            ["Employees.Detail.CreatedNote"] = "Employee created. You can now add documents, history and salary details on the tabs above.",
            ["Employees.Detail.SavedNote"] = "Employee details saved.",
            // Departments
            ["Departments.Header"] = "Departments",
            ["Departments.Column.Code"] = "Code",
            ["Departments.Column.Name"] = "Name",
            ["Departments.Column.Parent"] = "Parent",
            ["Departments.Column.Type"] = "Type",
            ["Departments.Label.Code"] = "Code",
            ["Departments.Label.Name"] = "Department Name",
            ["Departments.Label.Type"] = "Type",
            ["Departments.Label.ParentHint"] = "Parent Department (leave blank = this is a main department)",
            ["Departments.Error.LoadDepartments"] = "Could not load departments: {0}",
            ["Departments.Validation.CodeAndNameRequired"] = "Code and department name are required.",
            ["Departments.Validation.CircularParent"] = "This would create a circular reference (the selected parent is already a sub-department of this one).",
            ["Departments.Error.SaveFailed"] = "Save failed: {0}",
            ["Departments.Error.DeleteFailed"] = "Delete failed (it may still be referenced by positions/employees): {0}",
            ["Departments.Delete.Confirm"] = "Delete department '{0}'? Positions and employees referencing it must be removed first.",
            ["Departments.Button.New"] = "New",
            ["Departments.Button.Save"] = "Save",
            ["Departments.Button.Delete"] = "Delete",
            ["Departments.Positions.Title"] = "Job Positions",
            ["Departments.Positions.Subtitle"] = "Showing positions for the department selected on the left (select a department, or 'New' to see all).",
            ["Departments.Positions.Col.Title"] = "Title",
            ["Departments.Positions.Col.Department"] = "Department",
            ["Departments.Positions.Field.Title"] = "Position Title",
            ["Departments.Positions.Field.Department"] = "Department",
            ["Departments.Positions.Field.Description"] = "Job Description",

            // Positions
            ["Positions.Header"] = "Job Positions",
            ["Positions.Description"] = "Showing positions for the department selected on the left (select a department, or 'New' to see all).",
            ["Positions.Column.Code"] = "Code",
            ["Positions.Column.Title"] = "Title",
            ["Positions.Column.Department"] = "Department",
            ["Positions.Label.Code"] = "Code",
            ["Positions.Label.Title"] = "Position Title",
            ["Positions.Label.Department"] = "Department",
            ["Positions.Label.Description"] = "Job Description",
            ["Departments.Validation.PositionTitleRequired"] = "Position title and department are required.",
            ["Departments.Error.PositionSaveFailed"] = "Save failed: {0}",
            ["Departments.Error.PositionDeleteFailed"] = "Delete failed (it may still be referenced by employees): {0}",
            ["Positions.Delete.Confirm"] = "Delete position '{0}'?",
            ["Gender.Male"] = "Male",
            ["Gender.Female"] = "Female",
            ["EmploymentType.FullTime"] = "Full-time",
            ["EmploymentType.PartTime"] = "Part-time",
            ["EmploymentType.Contract"] = "Contract",
            ["EmploymentStatus.Active"] = "Active",
            ["EmploymentStatus.Terminated"] = "Terminated",
            ["InsuranceStatus.Insured"] = "Insured",
            ["InsuranceStatus.NotInsured"] = "Not Insured",
            ["Employees.Error.CouldNotLoad"] = "Could not load employees. Check your SQL Server connection string in DatabaseHelper.cs.\n\n{0}",
            ["Attendance.Edit.CheckoutTime"] = "Check-out (HH:mm)",
            ["Attendance.Edit.Shift"] = "Shift (auto-detected)",
            ["Attendance.Button.ForceRecalculate"] = "Force Recalculate",
            ["Attendance.Label.Status"] = "Status (auto)",
            ["Attendance.Status.Present"] = "Present",
            ["Attendance.Status.Absent"] = "Absent",
            ["Attendance.Status.Late"] = "Late",
            ["Attendance.Status.Leave"] = "Leave",
            ["Attendance.Status.Holiday"] = "Holiday",
            ["Attendance.Status.Weekend"] = "Weekend",
            ["Attendance.Label.MinutesLate"] = "Minutes Late",
            ["Attendance.Label.MinutesEarlyLeave"] = "Minutes Early Leave",
            ["Attendance.Label.WorkingHours"] = "Working Hours",
            ["Attendance.Label.Overtime"] = "Overtime (hrs)",
            ["Attendance.Approved"] = "Approved",
            ["Attendance.Button.New"] = "New",
            ["Attendance.Button.SaveManual"] = "Save (manual override)",
            ["Attendance.Button.Delete"] = "Delete",
            ["Attendance.Template.Saved"] = "Template saved.",
            ["Attendance.Dialog.OpenTitle"] = "Select attendance Excel file",
            ["Attendance.Dialog.SaveTemplateTitle"] = "Save attendance import template",
            ["Attendance.Dialog.Filter.ExcelFiles"] = "Excel Files (*.xlsx)|*.xlsx",
            ["Attendance.Import.RowsProcessed"] = "Rows processed: {0}",
            ["Attendance.Import.Inserted"] = "Inserted: {0}",
            ["Attendance.Import.Updated"] = "Updated: {0}",
            ["Attendance.Import.Errors"] = "Errors: {0}",
            ["Attendance.Import.FirstIssues"] = "First issues:",
            ["Attendance.Import.RowIssue"] = "  Row {0}: {1}",
            ["Attendance.Import.AndMore"] = "  ...and {0} more.",
            ["Attendance.Import.CompleteTitle"] = "Import Complete",
            ["Attendance.Import.Failure"] = "Import failed: {0}\n\nMake sure the file is a valid .xlsx with columns: EmployeeCode, CheckinDate, Checkin, CheckoutDate, Checkout, Shift.",
            ["Attendance.Save.Validation"] = "Employee and check-in date are required.",
            ["Attendance.Save.Success"] = "✓ Saved manually at {0}.",
            ["Attendance.Save.Failed"] = "Save failed: {0}",
            ["Attendance.Delete.Confirm"] = "Delete this attendance record?",
            ["Attendance.Delete.Failed"] = "Delete failed: {0}",
            ["Common.Done"] = "Done",
            ["Common.Error"] = "Error",
            ["Common.Confirm"] = "Confirm",
            ["Common.Validation"] = "Validation",
            ["Attendance.Summary.Format"] = "Total records: {0}   |   Present: {1}   |   Late: {2}   |   Absent: {3}   |   Leave: {4}   |   Total Overtime: {5:0.##} hrs",
            ["Attendance.Error.Title"] = "Database Error",
            ["Attendance.Error.CouldNotLoadShifts"] = "Could not load shifts: {0}",
            ["Attendance.Error.CouldNotLoadEmployees"] = "Could not load employees: {0}",
            ["Attendance.Error.CouldNotSaveTemplate"] = "Could not save template: {0}",
            ["Attendance.AutoSave.Info"] = "Status/Late/Early/Overtime/Weekend/Holiday/Leave are calculated and saved automatically as you type — no button needed.",
            ["Attendance.AutoSave.Locked"] = "🔒 This record is Approved — automatic recalculation is disabled. Edit the fields yourself and click \"Save (manual override)\" if you need to change it.",
            ["Attendance.AutoSave.NothingSaved"] = "Nothing saved yet — enter a check-in/check-out time to record this day automatically.",
            // Dashboard
            ["Dashboard.Header"] = "Dashboard",
            ["Dashboard.Refresh"] = "⟳  Refresh",
            ["Dashboard.ActiveEmployees"] = "Active Employees",
            ["Dashboard.PresentToday"] = "Present Today",
            ["Dashboard.LateToday"] = "Late Today",
            ["Dashboard.AbsentToday"] = "Absent Today",
            ["Dashboard.OnLeaveToday"] = "On Leave Today",
            ["Dashboard.PendingLeaveRequests"] = "Pending Leave Requests",
            ["Dashboard.Departments"] = "Departments",
            ["Dashboard.MonthPayroll.Generated"] = "This Month's Net Payroll",
            ["Dashboard.MonthPayroll.NotGenerated"] = "This Month's Net Payroll (not generated yet)",
            ["Dashboard.HeadcountByDepartment"] = "Headcount by Department",
            ["Dashboard.UpcomingHolidays"] = "Upcoming Holidays",
            ["Dashboard.NoUpcomingHolidays"] = "No upcoming holidays.",
            ["Dashboard.PendingLeaveHeader"] = "Pending Leave Requests",
            ["Dashboard.NoPendingLeaveRequests"] = "No pending leave requests.",
            ["Dashboard.Error.CouldNotLoad"] = "Could not load dashboard data: {0}",
            ["Leave.Default"] = "Leave",
            // Leave & Holidays screen
            ["Leave.Title"] = "Leave & Holidays Management",
            ["Leave.Tab.Requests"] = "Leave / Mission / Permit Requests",
            ["Leave.Tab.Holidays"] = "Company Holidays",
            ["Leave.Col.Code"] = "Code",
            ["Leave.Col.Employee"] = "Employee",
            ["Leave.Col.Type"] = "Type",
            ["Leave.Col.Start"] = "Start",
            ["Leave.Col.End"] = "End",
            ["Leave.Col.Reason"] = "Reason",
            ["Leave.Col.Status"] = "Status",
            ["Leave.Field.Employee"] = "Employee",
            ["Leave.Field.Type"] = "Type",
            ["Leave.Field.StartDate"] = "Start Date",
            ["Leave.Field.EndDate"] = "End Date",
            ["Leave.Field.Reason"] = "Reason",
            ["Leave.PaidNote"] = "Official Mission and Departure Permit are treated as paid time off, same as Annual/Sick Leave — only Unpaid Leave is deducted from pay. All approved types here automatically mark the employee's Attendance as a day off.",
            ["Leave.Balance.OK"] = "Remaining Annual Leave balance: {0} day(s).",
            ["Leave.Balance.Low"] = "Only {0} day(s) of Annual Leave remain this year.",
            ["Leave.Balance.AlreadyExhausted"] = "This employee's Annual Leave balance for this year is exhausted.",
            ["Leave.Balance.WouldExceed"] = "Only {0} day(s) of Annual Leave remain, but this request is for {1} day(s).",
            ["Leave.Balance.BlockMessage"] = "This request can't be submitted: only {0} day(s) of Annual Leave remain, but {1} day(s) were requested.",
            ["Leave.Button.New"] = "New Request",
            ["Leave.Button.Submit"] = "Submit Request",
            ["Leave.Button.Approve"] = "Approve",
            ["Leave.Button.Reject"] = "Reject",
            ["Leave.Button.Delete"] = "Delete",
            ["Leave.Balance.Header"] = "Employee Leave Balance Summary (Current Year)",
            ["Leave.Balance.Note"] = "Annual Leave entitlement, carry-over, usage and remaining balance for every active employee for the current year.",
            ["Leave.Balance.Refresh"] = "⟳  Refresh",
            ["Leave.Balance.Col.Code"] = "Code",
            ["Leave.Balance.Col.Employee"] = "Employee",
            ["Leave.Balance.Col.Entitlement"] = "Entitlement (Year)",
            ["Leave.Balance.Col.CarriedOver"] = "Carried Over",
            ["Leave.Balance.Col.TotalAvailable"] = "Total Available",
            ["Leave.Balance.Col.UsedThisYear"] = "Used This Year",
            ["Leave.Balance.Col.Remaining"] = "Remaining Balance",
            ["Leave.Holidays.Col.Date"] = "Date",
            ["Leave.Holidays.Col.Description"] = "Description",
            ["Leave.Holidays.Field.Date"] = "Date",
            ["Leave.Holidays.Field.Description"] = "Description",
            ["Leave.Holidays.Button.New"] = "New",
            ["Leave.Holidays.Button.Save"] = "Save",
            ["Leave.Holidays.Button.Delete"] = "Delete",
            ["Leave.Type.Annual"] = "Annual Leave",
            ["Leave.Type.Sick"] = "Sick Leave",
            ["Leave.Type.Unpaid"] = "Unpaid Leave",
            ["Leave.Type.Maternity"] = "Maternity/Paternity Leave",
            ["Leave.Type.Mission"] = "Official Mission",
            ["Leave.Type.Permit"] = "Departure Permit",

            // Payroll screen
            ["Payroll.Title"] = "Payroll",
            ["Payroll.Field.Month"] = "Month:",
            ["Payroll.Button.AutoGenerate"] = "Auto-Generate for All Employees",
            ["Payroll.Col.Code"] = "Code",
            ["Payroll.Col.Employee"] = "Employee",
            ["Payroll.Col.PeriodStart"] = "Period Start",
            ["Payroll.Col.PeriodEnd"] = "Period End",
            ["Payroll.Col.Basic"] = "Basic",
            ["Payroll.Col.Allowances"] = "Allowances",
            ["Payroll.Col.Deductions"] = "Deductions",
            ["Payroll.Col.OtAmount"] = "OT Amount",
            ["Payroll.Col.NetSalary"] = "Net Salary",
            ["Payroll.Col.Status"] = "Status",
            ["Payroll.Field.Employee"] = "Employee",
            ["Payroll.Field.PeriodStart"] = "Period Start",
            ["Payroll.Field.PeriodEnd"] = "Period End",
            ["Payroll.Field.BasicSalary"] = "Basic Salary",
            ["Payroll.Field.Allowances"] = "Allowances",
            ["Payroll.Field.Deductions"] = "Deductions",
            ["Payroll.Field.OvertimeHours"] = "Overtime Hours",
            ["Payroll.Field.OvertimeAmount"] = "Overtime Amount",
            ["Payroll.Button.New"] = "New",
            ["Payroll.Button.SaveManual"] = "Save Manual Entry",
            ["Payroll.Button.MarkPaid"] = "Mark as Paid",
            ["Payroll.Button.PrintPayslip"] = "🖨  Print Payslip",
            ["Payroll.Button.Delete"] = "Delete",
            // Shifts screen
            ["Shifts.Title"] = "Shifts",
            ["Shifts.Ws.Title"] = "Work Shift Templates",
            ["Shifts.Col.Name"] = "Name",
            ["Shifts.Col.Start"] = "Start",
            ["Shifts.Col.End"] = "End",
            ["Shifts.Col.LateTol"] = "Late Tol.",
            ["Shifts.Ws.Col.TotalHrs"] = "Total Hrs",
            ["Shifts.Field.Name"] = "Shift Name",
            ["Shifts.Ws.Field.Name"] = "Name",
            ["Shifts.Field.WorkingHours"] = "Working Hours",
            ["Shifts.Field.StartTime"] = "Start Time (HH:mm)",
            ["Shifts.Field.EndTime"] = "End Time (HH:mm)",
            ["Shifts.Field.LateTol"] = "Late Tolerance (min)",
            ["Shifts.Field.EarlyTol"] = "Early Leave Tolerance (min)",
            ["Shifts.Field.OtGrace"] = "Overtime Grace (min)",
            ["Shifts.Field.DetectStart"] = "Detection Window Start (HH:mm, optional)",
            ["Shifts.Field.DetectEnd"] = "Detection Window End (HH:mm, optional)",
            ["Shifts.Field.DetectionNote"] = "Leave both blank to auto-detect this shift by whichever shift's Start Time is closest to the check-in — the usual choice. Set an explicit window here only if two shifts start close enough together that a check-in could be ambiguous.",
            ["Shifts.Validation.DetectionBothOrNeither"] = "Set both detection window fields, or leave both blank.",
            ["Shifts.Ws.Field.Break"] = "Break (min)",
            ["Shifts.Ws.Field.TotalHours"] = "Total Hours",
            ["Shifts.Button.New"] = "New",
            ["Shifts.Button.Save"] = "Save",
            ["Shifts.Button.Delete"] = "Delete",

            // Cash Advances screen
            ["CashAdvances.Title"] = "Cash Advances",
            ["CashAdvances.Field.AsOf"] = "Balance as of:",
            ["CashAdvances.Col.Code"] = "Code",
            ["CashAdvances.Col.Employee"] = "Employee",
            ["CashAdvances.Col.Amount"] = "Amount",
            ["CashAdvances.Col.Installments"] = "Installments",
            ["CashAdvances.Col.Monthly"] = "Monthly",
            ["CashAdvances.Col.StartMonth"] = "Start Month",
            ["CashAdvances.Col.PaidSoFar"] = "Paid So Far",
            ["CashAdvances.Col.Remaining"] = "Remaining",
            ["CashAdvances.Col.Status"] = "Status",
            ["CashAdvances.Field.Employee"] = "Employee",
            ["CashAdvances.Field.TotalAmount"] = "Total Amount",
            ["CashAdvances.Field.Installments"] = "Installments (months)",
            ["CashAdvances.Field.MonthlyAuto"] = "Monthly Deduction (auto)",
            ["CashAdvances.Field.StartMonth"] = "Start Month",
            ["CashAdvances.Field.Notes"] = "Notes",
            ["CashAdvances.AutoDeductNote"] = "One installment is deducted automatically from Payroll each month from the start month onward, until fully paid.",
            ["CashAdvances.Button.New"] = "New",
            ["CashAdvances.Button.Add"] = "Add Advance",
            ["CashAdvances.Button.MarkCompleted"] = "Mark Completed",
            ["CashAdvances.Button.Delete"] = "Delete",

            // Org Structure screen
            ["OrgStructure.Title"] = "Organizational Structure",
            ["OrgStructure.Refresh"] = "⟳  Refresh",
            ["OrgStructure.Tab.ByDepartment"] = "By Department",
            ["OrgStructure.Tab.ReportingLines"] = "Reporting Lines",
            ["OrgStructure.Tab.VacantRoles"] = "Vacant Roles",
            ["OrgStructure.ManagerLabel"] = "MANAGER",
            ["OrgStructure.NoEmployeesInDept"] = "No employees directly in this department.",
            ["OrgStructure.NoEmployeesInSubDept"] = "No employees in this sub-department.",
            ["OrgStructure.ReportingNote"] = "Who reports to whom, built from each employee's 'Reports To' field (Employees screen). Top level = employees with no manager set.",
            ["OrgStructure.VacantNote"] = "Positions defined in Departments & Positions that no active employee currently holds — open headcount to fill.",
            ["OrgStructure.Col.Department"] = "Department",
            ["OrgStructure.Col.Position"] = "Position",
            ["OrgStructure.Col.PositionCode"] = "Position Code",
            ["OrgStructure.NoVacancies"] = "No vacant positions — every defined position has at least one active employee.",
            ["OrgStructure.NoDepartment"] = "(No Department)",
            ["OrgStructure.EmployeeCountTotal"] = "{0} employee(s) total",
            ["OrgStructure.AcrossSubDepts"] = " across {0} sub-department(s)",
            ["OrgStructure.EmployeeCount"] = "{0} employee(s)",
            ["OrgStructure.DirectReports"] = "({0} direct report(s))",
            // Adjustments (Bonuses/Penalties/Incentives) screen
            ["Adjustments.Title"] = "Bonuses, Penalties & Incentives",
            ["Adjustments.Field.Month"] = "Month:",
            ["Adjustments.Col.Code"] = "Code",
            ["Adjustments.Col.Employee"] = "Employee",
            ["Adjustments.Col.Type"] = "Type",
            ["Adjustments.Col.Amount"] = "Amount",
            ["Adjustments.Col.Description"] = "Description",
            ["Adjustments.Col.Created"] = "Created",
            ["Adjustments.Field.Employee"] = "Employee",
            ["Adjustments.Field.Type"] = "Type",
            ["Adjustments.Field.Amount"] = "Amount",
            ["Adjustments.Field.Description"] = "Description",
            ["Adjustments.Note"] = "Bonus/Incentive add to this month's Allowances; Penalty adds to Deductions — automatically, next time payroll is generated for this month.",
            ["Adjustments.Button.Add"] = "Add",
            ["Adjustments.Button.Delete"] = "Delete Selected",
            ["Adjustments.type.Bonus"] = "Bonus",
            ["Adjustments.type.Incentive"] = "Incentive",
            ["Adjustments.type.Penalty"] = "Penalty",

            // Common (shared across dialogs)
            ["Common.Ok"] = "OK",
            ["Common.Cancel"] = "Cancel",
            ["Common.Info"] = "Info",

            // Documents screen (general library — Important/Free/Other, not tied to an employee)
            ["Documents.Title"] = "Documents",
            ["Documents.Button.Import"] = "Import...",
            ["Documents.Field.IconSize"] = "Icon size:",
            ["Documents.Filter.All"] = "All",
            ["Documents.Category.Important"] = "Important Documents",
            ["Documents.Category.Free"] = "Free Documents",
            ["Documents.Category.Other"] = "Other",
            ["Documents.NoDocuments"] = "No documents in this category yet.",
            ["Documents.Sort.Button"] = "⇅ Sort",
            ["Documents.Sort.NameAsc"] = "Name (A → Z)",
            ["Documents.Sort.NameDesc"] = "Name (Z → A)",
            ["Documents.Sort.DateNewest"] = "Date (Newest first)",
            ["Documents.Sort.DateOldest"] = "Date (Oldest first)",
            ["Documents.Sort.SizeLargest"] = "Size (Largest first)",
            ["Documents.Sort.SizeSmallest"] = "Size (Smallest first)",
            ["Documents.Sort.Type"] = "File Type",
            ["Documents.Button.Open"] = "Open",
            ["Documents.Button.Print"] = "Print",
            ["Documents.Button.Rename"] = "Rename",
            ["Documents.Button.Delete"] = "Delete",
            ["Documents.Field.Name"] = "File Name",
            ["Documents.Field.Category"] = "Category",
            ["Documents.Dialog.SelectFileTitle"] = "Select a file to import",
            ["Documents.Dialog.Filter.AllFiles"] = "All Files (*.*)|*.*",
            ["Documents.Dialog.ImportTitle"] = "Import Document",
            ["Documents.Dialog.RenameTitle"] = "Rename Document",
            ["Documents.Validation.NameRequired"] = "File name cannot be empty.",
            ["Documents.Confirm.Delete"] = "Delete '{0}'? This also removes the stored copy from disk.",
            ["Documents.Error.LoadFailed"] = "Could not load documents: {0}",
            ["Documents.Error.ImportFailed"] = "Import failed: {0}",
            ["Documents.Error.OpenFailed"] = "Could not open the file: {0}",
            ["Documents.Error.PrintFailed"] = "Could not print the file: {0}",
            ["Documents.Error.RenameFailed"] = "Rename failed: {0}",
            ["Documents.Error.DeleteFailed"] = "Delete failed: {0}",
            ["Documents.Error.FileMissing"] = "This file could not be found on disk (it may have been moved or deleted).",

            // Employment history event types (EmploymentHistoryEntry.EventTypeDefinitions) —
            // canonical values stay in EmploymentHistoryEntry.EventTypeDefinitions; these are
            // display-only translations, looked up by key, never stored.
            ["HistoryEventType.Hire"] = "Hire",
            ["HistoryEventType.Promotion"] = "Promotion",
            ["HistoryEventType.DepartmentTransfer"] = "Department Transfer",
            ["HistoryEventType.PositionChange"] = "Position Change",
            ["HistoryEventType.SalaryChange"] = "Salary Change",
            ["HistoryEventType.PerformanceReview"] = "Performance Review",
            ["HistoryEventType.Termination"] = "Termination",
            ["HistoryEventType.Rehire"] = "Rehire",
            ["HistoryEventType.Other"] = "Other",

            // Employee document categories (EmployeeDocument.CategoryDefinitions) — canonical
            // values stay in EmployeeDocument.CategoryDefinitions (and the database's
            // CK_EmployeeDocuments_type constraint); these are display-only translations.
            ["EmployeeDocCategory.NationalId"] = "National ID Card",
            ["EmployeeDocCategory.BirthCertificate"] = "Birth Certificate",
            ["EmployeeDocCategory.PersonalPhoto"] = "Personal Photo",
            ["EmployeeDocCategory.GraduationCertificate"] = "Graduation Certificate",
            ["EmployeeDocCategory.CriminalRecord"] = "Criminal Record (Fish)",
            ["EmployeeDocCategory.MilitaryStatus"] = "Military Status Certificate",
            ["EmployeeDocCategory.LaborOfficeCard"] = "Labor Office Card (Kaab Amal)",
            ["EmployeeDocCategory.SocialInsurance"] = "Social Insurance Printout (Taameenat)",
            ["EmployeeDocCategory.MedicalFitness"] = "Medical Fitness Certificate",
            ["EmployeeDocCategory.Contract"] = "Contract",
            ["EmployeeDocCategory.Other"] = "Other",

        };

        // Insert English attendance strings into the English dictionary above by reopening it.

        private static readonly Dictionary<string, string> Arabic = new()
        {
            ["AppTitle"] = "الموارد البشرية",
            ["AppSubtitle"] = "نظام الموارد البشرية",

            ["Nav.Dashboard"] = "📊  لوحة التحكم",
            ["Nav.Employees"] = "👤  الموظفون",
            ["Nav.Departments"] = "🏢  الأقسام والوظائف",
            ["Nav.OrgStructure"] = "🌳  الهيكل التنظيمي",
            ["Nav.Shifts"] = "🕐  الورديات",
            ["Nav.Attendance"] = "🗓  الحضور والانصراف",
            ["Nav.Leave"] = "✈  الإجازات والعطلات",
            ["Nav.Adjustments"] = "🎁  المكافآت والجزاءات",
            ["Nav.CashAdvances"] = "💳  السلف المالية",
            ["Nav.Payroll"] = "💵  الرواتب",
            ["Nav.Documents"] = "🗂  المستندات",
            ["Nav.Settings"] = "⚙  الإعدادات",
            ["Nav.SignOut"] = "🚪  تسجيل الخروج",

            ["Login.Title"] = "نظام الموارد البشرية — تسجيل الدخول",
            ["Login.Username"] = "اسم المستخدم",
            ["Login.Password"] = "كلمة المرور",
            ["Login.SignIn"] = "تسجيل الدخول",
            ["Login.InvalidCredentials"] = "اسم المستخدم أو كلمة المرور غير صحيحة، أو أن هذا الحساب معطل.",
            ["Login.Required"] = "الرجاء إدخال اسم المستخدم وكلمة المرور.",

            ["Settings.Title"] = "الإعدادات",
            ["Settings.Tab.Users"] = "المستخدمون",
            ["Settings.Tab.Roles"] = "الأدوار والصلاحيات",
            ["Settings.Tab.Language"] = "اللغة",
            ["Settings.Users.Username"] = "اسم المستخدم",
            ["Settings.Users.FullName"] = "الاسم الكامل",
            ["Settings.Users.Employee"] = "الموظف المرتبط (اختياري)",
            ["Settings.Users.Role"] = "الدور",
            ["Settings.Users.Active"] = "نشط",
            ["Settings.Users.Password"] = "كلمة المرور",
            ["Settings.Users.New"] = "جديد",
            ["Settings.Users.Save"] = "حفظ",
            ["Settings.Users.Delete"] = "حذف",
            ["Settings.Users.ResetPassword"] = "إعادة تعيين كلمة المرور",
            ["Settings.Roles.Name"] = "اسم الدور",
            ["Settings.Roles.Description"] = "الوصف",
            ["Settings.Roles.Module"] = "الوحدة",
            ["Settings.Roles.CanView"] = "يمكنه العرض",
            ["Settings.Roles.CanEdit"] = "يمكنه الإضافة / التعديل / الحذف",
            ["Settings.Roles.New"] = "جديد",
            ["Settings.Roles.Save"] = "حفظ",
            ["Settings.Roles.Delete"] = "حذف",
            ["Settings.Roles.SavePermissions"] = "حفظ الصلاحيات",
            ["Settings.Language.Prompt"] = "اختر لغة التطبيق:",
            ["Settings.Language.English"] = "English (الإنجليزية)",
            ["Settings.Language.Arabic"] = "العربية",
            ["Settings.Language.Apply"] = "تطبيق",
            ["Settings.Language.RestartNote"] = "يسري فورًا دون الحاجة لإعادة التشغيل.",
            // Employees
            ["Employees.Header"] = "الموظفون",
            ["Employees.Search"] = "بحث",
            ["Employees.Refresh"] = "تحديث",
            ["Employees.Filter.Department"] = "القسم:",
            ["Employees.Filter.AllDepartments"] = "كل الأقسام",
            ["Employees.SelectedBanner"] = "التعديل على: {0}  (الكود: {1})",
            ["Employees.Column.Code"] = "الرمز",
            ["Employees.Column.Name"] = "الاسم",
            ["Employees.Column.Department"] = "القسم",
            ["Employees.Column.Position"] = "الوظيفة",
            ["Employees.Column.Email"] = "البريد الإلكتروني",
            ["Employees.Column.Phone"] = "الهاتف",
            ["Employees.Column.HireDate"] = "تاريخ التوظيف",
            ["Employees.Column.Status"] = "الحالة",
            ["Employees.Edit.Header"] = "إضافة / تعديل موظف",
            ["Employees.Edit.EmployeeCode"] = "رمز الموظف",
            ["Employees.Edit.FullName"] = "الاسم الكامل",
            ["Employees.Edit.Gender"] = "الجنس",
            ["Employees.Edit.Dob"] = "تاريخ الميلاد",
            ["Employees.Edit.Email"] = "البريد الإلكتروني",
            ["Employees.Edit.Phone"] = "الهاتف",
            ["Employees.Edit.HireDate"] = "تاريخ التوظيف",
            ["Employees.Edit.NationalId"] = "الهوية الوطنية",
            ["Employees.Edit.Department"] = "القسم",
            ["Employees.Edit.Position"] = "الوظيفة",
            ["Employees.Edit.EmploymentType"] = "نوع التوظيف",
            ["Employees.Edit.EmploymentStatus"] = "حالة التوظيف",
            ["Employees.Edit.Address"] = "العنوان",
            ["Employees.Edit.Weekend1"] = "يوم العطلة 1",
            ["Employees.Edit.Weekend2"] = "يوم العطلة 2",
            ["Employees.Edit.MaritalStatus"] = "الحالة الاجتماعية",
            ["Employees.Edit.BasicSalary"] = "الراتب الأساسي",
            ["Employees.Edit.Allowance"] = "البدلات",
            ["Employees.Edit.OvertimeRate"] = "سعر الإضافي (لكل ساعة)",
            ["Employees.Edit.LateDeductionRate"] = "خصم التأخير (لكل ساعة)",
            ["Employees.Edit.AnnualLeaveDays"] = "أيام الإجازة السنوية/سنة",
            ["Employees.Edit.LeaveCarriedOver"] = "الإجازة المحمولة (أيام)",
            ["Employees.Edit.ReportsTo"] = "المشرف",
            ["Employees.Edit.InsuranceStatus"] = "الحالة التأمينية",
            ["Employees.Button.New"] = "جديد",
            ["Employees.Button.Edit"] = "تعديل",
            ["Employees.Button.Save"] = "حفظ",
            ["Employees.Button.Delete"] = "حذف",
            ["Employees.Detail.WindowTitle"] = "الموظف",
            ["Employees.Detail.MainDataHeader"] = "بيانات الموظف",
            ["Employees.Detail.Tab.Details"] = "التفاصيل",
            ["Employees.Detail.Tab.Documents"] = "المستندات",
            ["Employees.Detail.Tab.History"] = "السجل الوظيفي",
            ["Employees.Detail.Tab.Salary"] = "الراتب",
            ["Employees.Detail.CreatedNote"] = "تم إنشاء الموظف. يمكنك الآن إضافة المستندات والسجل الوظيفي وتفاصيل الراتب من التبويبات أعلاه.",
            ["Employees.Detail.SavedNote"] = "تم حفظ بيانات الموظف.",
            // Departments (Arabic)
            ["Departments.Header"] = "الأقسام",
            ["Departments.Column.Code"] = "الرمز",
            ["Departments.Column.Name"] = "الاسم",
            ["Departments.Column.Parent"] = "الأب",
            ["Departments.Column.Type"] = "النوع",
            ["Departments.Label.Code"] = "الرمز",
            ["Departments.Label.Name"] = "اسم القسم",
            ["Departments.Label.Type"] = "النوع",
            ["Departments.Label.ParentHint"] = "القسم الأب (اتركه فارغًا = هذا قسم رئيسي)",
            ["Departments.Error.LoadDepartments"] = "تعذر تحميل الأقسام: {0}",
            ["Departments.Validation.CodeAndNameRequired"] = "الرمز واسم القسم مطلوبان.",
            ["Departments.Validation.CircularParent"] = "سيؤدي هذا إلى إنشاء إشارة دائرية (القسم المختار أصبح بالفعل قسمًا فرعيًا لهذا القسم).",
            ["Departments.Error.SaveFailed"] = "فشل الحفظ: {0}",
            ["Departments.Error.DeleteFailed"] = "فشل الحذف (قد يظل مشارًا إليه من قبل الوظائف/الموظفين): {0}",
            ["Departments.Delete.Confirm"] = "حذف القسم '{0}'؟ يجب إزالة المناصب والموظفين المشارين إليه أولاً.",
            ["Departments.Button.New"] = "جديد",
            ["Departments.Button.Save"] = "حفظ",
            ["Departments.Button.Delete"] = "حذف",
            ["Departments.Positions.Title"] = "الوظائف",
            ["Departments.Positions.Subtitle"] = "عرض الوظائف الخاصة بالقسم المحدد على اليسار (اختر قسمًا، أو 'جديد' لعرض الكل).",
            ["Departments.Positions.Col.Title"] = "المسمى الوظيفي",
            ["Departments.Positions.Col.Department"] = "القسم",
            ["Departments.Positions.Field.Title"] = "المسمى الوظيفي",
            ["Departments.Positions.Field.Department"] = "القسم",
            ["Departments.Positions.Field.Description"] = "الوصف الوظيفي",

            // Positions (Arabic)
            ["Positions.Header"] = "المناصب الوظيفية",
            ["Positions.Description"] = "عرض المناصب للقسم المحدد على اليسار (اختر قسمًا، أو 'جديد' لعرض الكل).",
            ["Positions.Column.Code"] = "الرمز",
            ["Positions.Column.Title"] = "المسمى الوظيفي",
            ["Positions.Column.Department"] = "القسم",
            ["Positions.Label.Code"] = "الرمز",
            ["Positions.Label.Title"] = "المسمى الوظيفي",
            ["Positions.Label.Department"] = "القسم",
            ["Positions.Label.Description"] = "الوصف الوظيفي",
            ["Departments.Validation.PositionTitleRequired"] = "المسمى الوظيفي والقسم مطلوبان.",
            ["Departments.Error.PositionSaveFailed"] = "فشل الحفظ: {0}",
            ["Departments.Error.PositionDeleteFailed"] = "فشل الحذف (قد يظل مشارًا إليه من قبل الموظفين): {0}",
            ["Positions.Delete.Confirm"] = "حذف المنصب '{0}'؟",
            ["Gender.Male"] = "ذكر",
            ["Gender.Female"] = "أنثى",
            ["EmploymentType.FullTime"] = "دوام كامل",
            ["EmploymentType.PartTime"] = "دوام جزئي",
            ["EmploymentType.Contract"] = "عقد",
            ["EmploymentStatus.Active"] = "نشط",
            ["EmploymentStatus.Terminated"] = "منهي",
            ["InsuranceStatus.Insured"] = "مؤمن",
            ["InsuranceStatus.NotInsured"] = "غير مؤمن",
            ["Employees.Error.CouldNotLoad"] = "تعذر تحميل الموظفين. تحقق من سلسلة اتصال SQL Server في DatabaseHelper.cs.\n\n{0}",
            // Documents & History (Arabic)
            ["Employees.Documents.Header"] = "مركز المستندات الشخصية",
            ["Employees.Documents.Hint"] = "اختر موظفًا أعلاه لعرض أو استيراد مستنداته.",
            ["Employees.Documents.Description"] = "تخزين المستندات لكل موظف بأمان — الهوية، الشهادات، والصور، والعقود. تُنسخ الملفات إلى مجلد EmployeeDocuments الخاص بالتطبيق.",
            ["Employees.Documents.Column.Category"] = "الفئة",
            ["Employees.Documents.Column.FileName"] = "اسم الملف",
            ["Employees.Documents.Column.Description"] = "الوصف",
            ["Employees.Documents.Column.Uploaded"] = "تاريخ الرفع",
            ["Employees.Documents.TypeTooltip"] = "الفئة للمستند الذي سيتم استيراده",
            ["Employees.Documents.DescriptionTooltip"] = "وصف اختياري للمستند المستورد",
            ["Employees.Documents.ImportButton"] = "\uD83D\uDCCE  استيراد مستند...",
            ["Employees.Documents.ViewButton"] = "\uD83D\uDC41  عرض / إعادة تسمية / تحرير",
            ["Employees.Documents.DeleteButton"] = "حذف المحدد",
            ["Employees.History.Header"] = "سجل التوظيف (الترقيات / تاريخ العمل / التنقل الداخلي / الأداء)",
            ["Employees.History.Hint"] = "اختر موظفًا أعلاه لعرض سجل التوظيف.",
            ["Employees.History.Description"] = "يتم تسجيل تحويلات الأقسام / تغييرات المناصب / تغييرات الراتب تلقائيًا عند تعديل الحقول وحفظها أعلاه. تُسجل مراجعات الأداء يدويًا أدناه.",
            ["Employees.History.Column.Date"] = "التاريخ",
            ["Employees.History.Column.Event"] = "الحدث",
            ["Employees.History.Column.Change"] = "التغيير",
            ["Employees.History.Column.Notes"] = "ملاحظات",
            ["Employees.History.Column.Recorded"] = "المسجل",
            ["Employees.History.EventType"] = "نوع الحدث",
            ["Employees.History.EventDate"] = "تاريخ الحدث",
            ["Employees.History.Notes"] = "ملاحظات",
            ["Employees.History.Performance"] = "تقييم الأداء (إن وجد)",
            ["Employees.History.Rating.Excellent"] = "ممتاز",
            ["Employees.History.Rating.Good"] = "جيد",
            ["Employees.History.Rating.Average"] = "متوسط",
            ["Employees.History.Rating.NeedsImprovement"] = "يحتاج تحسين",
            ["Employees.History.AddButton"] = "إضافة إدخال يدوي",
            ["Employees.History.DeleteButton"] = "حذف المحدد",

            // Salary Details expander
            ["Employees.Salary.Header"] = "تفاصيل الراتب",
            ["Employees.Salary.Hint"] = "اختر موظفًا أعلاه لعرض أو تعديل تفاصيل راتبه.",
            ["Employees.Salary.EntitlementsHeader"] = "الاستحقاقات",
            ["Employees.Salary.Basic"] = "الراتب الأساسي",
            ["Employees.Salary.FixedAllowance"] = "بدلات ثابتة",
            ["Employees.Salary.Completion"] = "استكمال الراتب",
            ["Employees.Salary.OtherEntitlements"] = "مستحقات أخرى",
            ["Employees.Salary.DeductionsHeader"] = "الاستقطاعات",
            ["Employees.Salary.InsuranceAmount"] = "التأمينات",
            ["Employees.Salary.MonthlyTax"] = "الضريبة الشهرية",
            ["Employees.Salary.InsuranceNote"] = "لا تُخصم التأمينات في الرواتب إلا عندما تكون الحالة التأمينية (أعلاه، في إضافة/تعديل الموظف) مضبوطة على مؤمن.",
            ["Employees.Salary.RatesHeader"] = "معدلات إضافية",
            ["Employees.Salary.OvertimeRate"] = "معدل الإضافي (لكل ساعة)",
            ["Employees.Salary.LateDeductionRate"] = "معدل خصم التأخير (لكل ساعة)",
            ["Employees.Salary.SaveButton"] = "حفظ تفاصيل الراتب",
            ["Employees.Salary.HistoryHeader"] = "سجل تعديلات الراتب",
            ["Employees.Salary.History.Date"] = "التاريخ",
            ["Employees.Salary.History.Insured"] = "مؤمن",
            ["Employees.Salary.History.ChangedBy"] = "تم التعديل بواسطة",
            ["Employees.Dialog.SelectDocumentTitle"] = "اختر المستند لاستيراده",
            ["Employees.Dialog.Filter.DocumentFiles"] = "كل الملفات (*.*)|*.*|PDF (*.pdf)|*.pdf|صور (*.jpg;*.jpeg;*.png)|*.jpg;*.jpeg;*.png|مستندات Word (*.doc;*.docx)|*.doc;*.docx",
            ["Employees.Info.SelectEmployeeFirst"] = "اختر موظفًا أولاً.",
            ["Employees.Info.SelectDocumentFirst"] = "اختر مستندًا أولاً.",
            ["Employees.Error.CouldNotLoadDocuments"] = "تعذر تحميل المستندات: {0}",
            ["Employees.Error.ImportFailed"] = "فشل الاستيراد: {0}",
            ["Employees.Error.CouldNotOpenDocument"] = "تعذر فتح المستند: {0}",
            ["Employees.Confirm.DeleteDocument"] = "حذف '{0}'؟ سيؤدي ذلك أيضًا إلى إزالة النسخة المخزنة من القرص.",
            ["Employees.Error.DeleteDocumentFailed"] = "فشل الحذف: {0}",
            // Dashboard
            ["Dashboard.Header"] = "لوحة التحكم",
            ["Dashboard.Refresh"] = "⟳  تحديث",
            ["Dashboard.ActiveEmployees"] = "الموظفون النشطون",
            ["Dashboard.PresentToday"] = "حاضر اليوم",
            ["Dashboard.LateToday"] = "متأخر اليوم",
            ["Dashboard.AbsentToday"] = "غائب اليوم",
            ["Dashboard.OnLeaveToday"] = "بإجازة اليوم",
            ["Dashboard.PendingLeaveRequests"] = "طلبات الإجازة المعلقة",
            ["Dashboard.Departments"] = "الأقسام",
            ["Dashboard.MonthPayroll.Generated"] = "صافي رواتب هذا الشهر",
            ["Dashboard.MonthPayroll.NotGenerated"] = "صافي رواتب هذا الشهر (لم يتم إنشاؤه بعد)",
            ["Dashboard.HeadcountByDepartment"] = "التعداد حسب القسم",
            ["Dashboard.UpcomingHolidays"] = "العطلات القادمة",
            ["Dashboard.NoUpcomingHolidays"] = "لا توجد عطلات قادمة.",
            ["Dashboard.PendingLeaveHeader"] = "طلبات الإجازة المعلقة",
            ["Dashboard.NoPendingLeaveRequests"] = "لا توجد طلبات إجازة معلقة.",
            ["Dashboard.Error.CouldNotLoad"] = "تعذر تحميل بيانات لوحة التحكم: {0}",
            ["Leave.Default"] = "إجازة",
            // Attendance extra
            ["Attendance.Dialog.OpenTitle"] = "اختر ملف الحضور (Excel)",
            ["Attendance.Dialog.SaveTemplateTitle"] = "حفظ قالب استيراد الحضور",
            ["Attendance.Dialog.Filter.ExcelFiles"] = "ملفات إكسل (*.xlsx)|*.xlsx",
            ["Attendance.Import.RowsProcessed"] = "عدد الصفوف المعالجة: {0}",
            ["Attendance.Import.Inserted"] = "تمت الإضافة: {0}",
            ["Attendance.Import.Updated"] = "تم التحديث: {0}",
            ["Attendance.Import.Errors"] = "أخطاء: {0}",
            ["Attendance.Import.FirstIssues"] = "أول المشكلات:",
            ["Attendance.Import.RowIssue"] = "  السطر {0}: {1}",
            ["Attendance.Import.AndMore"] = "  ...و {0} المزيد.",
            ["Attendance.Import.CompleteTitle"] = "انتهى الاستيراد",
            ["Attendance.Import.Failure"] = "فشل الاستيراد: {0}\n\nتأكد أن الملف بصيغة .xlsx وبالأعمدة: EmployeeCode, CheckinDate, Checkin, CheckoutDate, Checkout, Shift.",
            ["Attendance.Save.Validation"] = "الموظف وتاريخ الدخول مطلوبان.",
            ["Attendance.Save.Success"] = "✓ تم الحفظ يدويًا في {0}.",
            ["Attendance.Save.Failed"] = "فشل الحفظ: {0}",
            ["Attendance.Delete.Confirm"] = "حذف سجل الحضور هذا؟",
            ["Attendance.Delete.Failed"] = "فشل الحذف: {0}",
            ["Common.Done"] = "تم",
            ["Common.Error"] = "خطأ",
            ["Common.Confirm"] = "تأكيد",
            ["Common.Validation"] = "التحقق من الصحة",
            // Attendance view
            ["Attendance.Header"] = "الحضور والانصراف",
            ["Attendance.ImportExcel"] = "استيراد من إكسل...",
            ["Attendance.Report.Button"] = "طباعة تقرير...",
            ["Attendance.Report.Title"] = "تقرير الحضور",
            ["Attendance.Report.TypeLabel"] = "نوع التقرير",
            ["Attendance.Report.Type.Detailed"] = "سجل يومي تفصيلي",
            ["Attendance.Report.Type.EmployeeSummary"] = "ملخص شهري (لكل موظف)",
            ["Attendance.Report.Type.DepartmentSummary"] = "ملخص الأقسام",
            ["Attendance.Report.ScopeLabel"] = "النطاق",
            ["Attendance.Report.Scope.All"] = "جميع الموظفين",
            ["Attendance.Report.Scope.Employee"] = "موظف واحد:",
            ["Attendance.Report.Scope.Department"] = "قسم واحد:",
            ["Attendance.Report.DateRangeLabel"] = "النطاق الزمني",
            ["Attendance.Report.OutputLabel"] = "المخرجات",
            ["Attendance.Report.Output.Print"] = "طباعة",
            ["Attendance.Report.Output.Excel"] = "تصدير إلى إكسل",
            ["Attendance.Report.GenerateButton"] = "إنشاء",
            ["Attendance.Report.Validation.DateRange"] = "اختر نطاقًا زمنيًا صحيحًا (تاريخ النهاية بعد أو يساوي تاريخ البداية).",
            ["Attendance.Report.Validation.PickEmployee"] = "اختر موظفًا.",
            ["Attendance.Report.Validation.PickDepartment"] = "اختر قسمًا.",
            ["Attendance.Report.Sent"] = "تم إرسال التقرير إلى الطابعة.",
            ["Attendance.Report.SaveExcelTitle"] = "حفظ تقرير الحضور",
            ["Attendance.Report.ExcelSaved"] = "تم حفظ التقرير.",
            ["Attendance.Report.Error"] = "تعذّر إنشاء التقرير: {0}",
            ["Attendance.DownloadTemplate"] = "تحميل القالب",
            ["Attendance.Mode.ByDay"] = "يوم واحد، جميع الموظفين",
            ["Attendance.Mode.ByEmployee"] = "موظف واحد، نطاق التواريخ",
            ["Attendance.Filter.Date"] = "التاريخ:",
            ["Attendance.Filter.Employee"] = "الموظف:",
            ["Attendance.Filter.From"] = "من:",
            ["Attendance.Filter.To"] = "إلى:",
            ["Attendance.Button.ThisMonth"] = "هذا الشهر",
            ["Attendance.Column.Code"] = "الرمز",
            ["Attendance.Column.Employee"] = "الموظف",
            ["Attendance.Column.Date"] = "التاريخ",
            ["Attendance.Column.Day"] = "اليوم",
            ["Attendance.Column.Checkin"] = "دخول",
            ["Attendance.Column.Checkout"] = "خروج",
            ["Attendance.Column.Shift"] = "الوردية",
            ["Attendance.Column.Late"] = "تأخير (دقيقة)",
            ["Attendance.Column.Early"] = "انصراف مبكر (دقيقة)",
            ["Attendance.Column.Overtime"] = "ساعات إضافية",
            ["Attendance.Column.TotalHrs"] = "إجمالي الساعات",
            ["Attendance.Column.Status"] = "الحالة",
            ["Attendance.Column.Approved"] = "معتمد",
            ["Attendance.Summary.PickEmployee"] = "اختر موظفًا ونطاق تواريخ لعرض الحضور.",
            ["Attendance.Summary.Format"] = "إجمالي السجلات: {0}   |   الحاضر: {1}   |   المتأخر: {2}   |   الغائب: {3}   |   الإجازة: {4}   |   إجمالي الساعات الإضافية: {5:0.##} ساعة",
            ["Attendance.Edit.Header"] = "إضافة / تعديل سجل الحضور",
            ["Attendance.Edit.Employee"] = "الموظف",
            ["Attendance.Edit.CheckinDate"] = "تاريخ الدخول",
            ["Attendance.Edit.CheckinTime"] = "دخول (HH:mm)",
            ["Attendance.Edit.CheckoutTime"] = "خروج (HH:mm)",
            ["Attendance.Edit.Shift"] = "الوردية (مكتشفة آليًا)",
            ["Attendance.Button.ForceRecalculate"] = "إعادة الحساب",
            ["Attendance.Label.Status"] = "الحالة (آلي)",
            ["Attendance.Status.Present"] = "حاضر",
            ["Attendance.Status.Absent"] = "غائب",
            ["Attendance.Status.Late"] = "متأخر",
            ["Attendance.Status.Leave"] = "إجازة",
            ["Attendance.Status.Holiday"] = "عطلة",
            ["Attendance.Status.Weekend"] = "عطلة نهاية الأسبوع",
            ["Attendance.Label.MinutesLate"] = "دقائق التأخير",
            ["Attendance.Label.MinutesEarlyLeave"] = "دقائق الانصراف المبكر",
            ["Attendance.Label.WorkingHours"] = "ساعات العمل",
            ["Attendance.Label.Overtime"] = "ساعات إضافية",
            ["Attendance.Approved"] = "معتمد",
            ["Attendance.Button.New"] = "جديد",
            ["Attendance.Button.SaveManual"] = "حفظ (تجاوز يدوي)",
            ["Attendance.Button.Delete"] = "حذف",
            ["Attendance.Template.Saved"] = "تم حفظ القالب.",
            ["Attendance.Error.Title"] = "خطأ في قاعدة البيانات",
            ["Attendance.Error.CouldNotLoadShifts"] = "تعذر تحميل الورديات: {0}",
            ["Attendance.Error.CouldNotLoadEmployees"] = "تعذر تحميل الموظفين: {0}",
            ["Attendance.Error.CouldNotSaveTemplate"] = "تعذر حفظ القالب: {0}",
            ["Attendance.AutoSave.Info"] = "يتم حساب الحالة/التأخير/الانصراف المبكر/الإضافي/العطلة/الإجازة وحفظها تلقائيًا أثناء الكتابة — لا حاجة للاستخدام.",
            ["Attendance.AutoSave.Locked"] = "🔒 هذا السجل معتمد — تم تعطيل إعادة الحساب التلقائي. عدل الحقول يدويًا ثم اضغط \"حفظ (تجاوز يدوي)\" إذا أردت تغييره.",
            ["Attendance.AutoSave.NothingSaved"] = "لم يتم الحفظ بعد — أدخل وقت الدخول/الخروج لحفظ هذا اليوم تلقائيًا.",
            // Leave & Holidays screen
            ["Leave.Title"] = "إدارة الإجازات والعطلات",
            ["Leave.Tab.Requests"] = "طلبات الإجازة / المهمة / الإذن",
            ["Leave.Tab.Holidays"] = "عطلات الشركة",
            ["Leave.Col.Code"] = "الكود",
            ["Leave.Col.Employee"] = "الموظف",
            ["Leave.Col.Type"] = "النوع",
            ["Leave.Col.Start"] = "البداية",
            ["Leave.Col.End"] = "النهاية",
            ["Leave.Col.Reason"] = "السبب",
            ["Leave.Col.Status"] = "الحالة",
            ["Leave.Field.Employee"] = "الموظف",
            ["Leave.Field.Type"] = "النوع",
            ["Leave.Field.StartDate"] = "تاريخ البداية",
            ["Leave.Field.EndDate"] = "تاريخ النهاية",
            ["Leave.Field.Reason"] = "السبب",
            ["Leave.PaidNote"] = "تُعامل المهمة الرسمية وإذن الانصراف كإجازة مدفوعة الأجر، مثل الإجازة السنوية/المرضية تمامًا — يُخصم فقط من الإجازة غير مدفوعة الأجر من الراتب. جميع الأنواع المعتمدة هنا تُسجَّل تلقائيًا في الحضور كيوم إجازة.",
            ["Leave.Balance.OK"] = "الرصيد المتبقي من الإجازة السنوية: {0} يوم.",
            ["Leave.Balance.Low"] = "تبقى فقط {0} يوم من رصيد الإجازة السنوية لهذا العام.",
            ["Leave.Balance.AlreadyExhausted"] = "انتهى رصيد الإجازة السنوية لهذا الموظف لهذا العام.",
            ["Leave.Balance.WouldExceed"] = "المتبقي فقط {0} يوم من الإجازة السنوية، لكن هذا الطلب لمدة {1} يوم.",
            ["Leave.Balance.BlockMessage"] = "لا يمكن إرسال هذا الطلب: المتبقي فقط {0} يوم من الإجازة السنوية، بينما المطلوب {1} يوم.",
            ["Leave.Button.New"] = "طلب جديد",
            ["Leave.Button.Submit"] = "إرسال الطلب",
            ["Leave.Button.Approve"] = "اعتماد",
            ["Leave.Button.Reject"] = "رفض",
            ["Leave.Button.Delete"] = "حذف",
            ["Leave.Balance.Header"] = "ملخص رصيد إجازات الموظفين (السنة الحالية)",
            ["Leave.Balance.Note"] = "استحقاق الإجازة السنوية، الرصيد المرحّل، المستخدم، والرصيد المتبقي لكل موظف نشط عن السنة الحالية.",
            ["Leave.Balance.Refresh"] = "⟳  تحديث",
            ["Leave.Balance.Col.Code"] = "الكود",
            ["Leave.Balance.Col.Employee"] = "الموظف",
            ["Leave.Balance.Col.Entitlement"] = "الاستحقاق (سنويًا)",
            ["Leave.Balance.Col.CarriedOver"] = "المرحّل",
            ["Leave.Balance.Col.TotalAvailable"] = "الإجمالي المتاح",
            ["Leave.Balance.Col.UsedThisYear"] = "المستخدم هذا العام",
            ["Leave.Balance.Col.Remaining"] = "الرصيد المتبقي",
            ["Leave.Holidays.Col.Date"] = "التاريخ",
            ["Leave.Holidays.Col.Description"] = "الوصف",
            ["Leave.Holidays.Field.Date"] = "التاريخ",
            ["Leave.Holidays.Field.Description"] = "الوصف",
            ["Leave.Holidays.Button.New"] = "جديد",
            ["Leave.Holidays.Button.Save"] = "حفظ",
            ["Leave.Holidays.Button.Delete"] = "حذف",
            ["Leave.Type.Annual"] = "إجازة سنوية",
            ["Leave.Type.Sick"] = "إجازة مرضية",
            ["Leave.Type.Unpaid"] = "إجازة غير مدفوعة",
            ["Leave.Type.Maternity"] = "إجازة وضع/إجازة رعاية مولود",
            ["Leave.Type.Mission"] = "مأمورية رسمية",
            ["Leave.Type.Permit"] = "إذن الانصراف",

            // Payroll screen
            ["Payroll.Title"] = "الرواتب",
            ["Payroll.Field.Month"] = "الشهر:",
            ["Payroll.Button.AutoGenerate"] = "توليد تلقائي لجميع الموظفين",
            ["Payroll.Col.Code"] = "الكود",
            ["Payroll.Col.Employee"] = "الموظف",
            ["Payroll.Col.PeriodStart"] = "بداية الفترة",
            ["Payroll.Col.PeriodEnd"] = "نهاية الفترة",
            ["Payroll.Col.Basic"] = "الأساسي",
            ["Payroll.Col.Allowances"] = "البدلات",
            ["Payroll.Col.Deductions"] = "الخصومات",
            ["Payroll.Col.OtAmount"] = "مبلغ الإضافي",
            ["Payroll.Col.NetSalary"] = "صافي الراتب",
            ["Payroll.Col.Status"] = "الحالة",
            ["Payroll.Field.Employee"] = "الموظف",
            ["Payroll.Field.PeriodStart"] = "بداية الفترة",
            ["Payroll.Field.PeriodEnd"] = "نهاية الفترة",
            ["Payroll.Field.BasicSalary"] = "الراتب الأساسي",
            ["Payroll.Field.Allowances"] = "البدلات",
            ["Payroll.Field.Deductions"] = "الخصومات",
            ["Payroll.Field.OvertimeHours"] = "ساعات العمل الإضافي",
            ["Payroll.Field.OvertimeAmount"] = "مبلغ العمل الإضافي",
            ["Payroll.Button.New"] = "جديد",
            ["Payroll.Button.SaveManual"] = "حفظ إدخال يدوي",
            ["Payroll.Button.MarkPaid"] = "تحديد كمدفوع",
            ["Payroll.Button.PrintPayslip"] = "🖨  طباعة قسيمة الراتب",
            ["Payroll.Button.Delete"] = "حذف",
            // Shifts screen
            ["Shifts.Title"] = "الورديات",
            ["Shifts.Ws.Title"] = "قوالب ورديات العمل",
            ["Shifts.Col.Name"] = "الاسم",
            ["Shifts.Col.Start"] = "البداية",
            ["Shifts.Col.End"] = "النهاية",
            ["Shifts.Col.LateTol"] = "سماحية التأخير",
            ["Shifts.Ws.Col.TotalHrs"] = "إجمالي الساعات",
            ["Shifts.Field.Name"] = "اسم الوردية",
            ["Shifts.Ws.Field.Name"] = "الاسم",
            ["Shifts.Field.WorkingHours"] = "ساعات العمل",
            ["Shifts.Field.StartTime"] = "وقت البداية (HH:mm)",
            ["Shifts.Field.EndTime"] = "وقت النهاية (HH:mm)",
            ["Shifts.Field.LateTol"] = "سماحية التأخير (دقيقة)",
            ["Shifts.Field.EarlyTol"] = "سماحية الانصراف المبكر (دقيقة)",
            ["Shifts.Field.OtGrace"] = "فترة سماح العمل الإضافي (دقيقة)",
            ["Shifts.Field.DetectStart"] = "بداية نافذة الكشف (HH:mm، اختياري)",
            ["Shifts.Field.DetectEnd"] = "نهاية نافذة الكشف (HH:mm، اختياري)",
            ["Shifts.Field.DetectionNote"] = "اترك الحقلين فارغين لاكتشاف الوردية تلقائيًا حسب أقرب وقت بداية — وهو الخيار المعتاد. حدد نافذة صريحة هنا فقط إذا كانت وردتان تبدآن بوقتين متقاربين قد يسبب التباسًا عند تحديد الوردية من وقت الحضور.",
            ["Shifts.Validation.DetectionBothOrNeither"] = "حدد كلا حقلي نافذة الكشف، أو اتركهما فارغين معًا.",
            ["Shifts.Ws.Field.Break"] = "الاستراحة (دقيقة)",
            ["Shifts.Ws.Field.TotalHours"] = "إجمالي الساعات",
            ["Shifts.Button.New"] = "جديد",
            ["Shifts.Button.Save"] = "حفظ",
            ["Shifts.Button.Delete"] = "حذف",

            // Cash Advances screen
            ["CashAdvances.Title"] = "السلف المالية",
            ["CashAdvances.Field.AsOf"] = "الرصيد اعتبارًا من:",
            ["CashAdvances.Col.Code"] = "الكود",
            ["CashAdvances.Col.Employee"] = "الموظف",
            ["CashAdvances.Col.Amount"] = "المبلغ",
            ["CashAdvances.Col.Installments"] = "الأقساط",
            ["CashAdvances.Col.Monthly"] = "شهريًا",
            ["CashAdvances.Col.StartMonth"] = "شهر البداية",
            ["CashAdvances.Col.PaidSoFar"] = "المدفوع حتى الآن",
            ["CashAdvances.Col.Remaining"] = "المتبقي",
            ["CashAdvances.Col.Status"] = "الحالة",
            ["CashAdvances.Field.Employee"] = "الموظف",
            ["CashAdvances.Field.TotalAmount"] = "المبلغ الإجمالي",
            ["CashAdvances.Field.Installments"] = "الأقساط (بالأشهر)",
            ["CashAdvances.Field.MonthlyAuto"] = "الخصم الشهري (تلقائي)",
            ["CashAdvances.Field.StartMonth"] = "شهر البداية",
            ["CashAdvances.Field.Notes"] = "ملاحظات",
            ["CashAdvances.AutoDeductNote"] = "يُخصم قسط واحد تلقائيًا من الرواتب كل شهر ابتداءً من شهر البداية، حتى السداد الكامل.",
            ["CashAdvances.Button.New"] = "جديد",
            ["CashAdvances.Button.Add"] = "إضافة سلفة",
            ["CashAdvances.Button.MarkCompleted"] = "تحديد كمكتمل",
            ["CashAdvances.Button.Delete"] = "حذف",

            // Org Structure screen
            ["OrgStructure.Title"] = "الهيكل التنظيمي",
            ["OrgStructure.Refresh"] = "⟳  تحديث",
            ["OrgStructure.Tab.ByDepartment"] = "حسب القسم",
            ["OrgStructure.Tab.ReportingLines"] = "التسلسل الإداري",
            ["OrgStructure.Tab.VacantRoles"] = "الوظائف الشاغرة",
            ["OrgStructure.ManagerLabel"] = "المدير",
            ["OrgStructure.NoEmployeesInDept"] = "لا يوجد موظفون مباشرون في هذا القسم.",
            ["OrgStructure.NoEmployeesInSubDept"] = "لا يوجد موظفون في هذا القسم الفرعي.",
            ["OrgStructure.ReportingNote"] = "من يتبع من، بناءً على حقل 'يرفع تقاريره إلى' لكل موظف (شاشة الموظفين). المستوى الأعلى = الموظفون الذين لا يوجد لديهم مدير محدد.",
            ["OrgStructure.VacantNote"] = "الوظائف المعرّفة في الأقسام والوظائف والتي لا يشغلها حاليًا أي موظف نشط — شواغر متاحة للتعيين.",
            ["OrgStructure.Col.Department"] = "القسم",
            ["OrgStructure.Col.Position"] = "الوظيفة",
            ["OrgStructure.Col.PositionCode"] = "كود الوظيفة",
            ["OrgStructure.NoVacancies"] = "لا توجد وظائف شاغرة — كل وظيفة معرّفة يشغلها موظف نشط واحد على الأقل.",
            ["OrgStructure.NoDepartment"] = "(بدون قسم)",
            ["OrgStructure.EmployeeCountTotal"] = "{0} موظف إجمالاً",
            ["OrgStructure.AcrossSubDepts"] = " موزعين على {0} قسم فرعي",
            ["OrgStructure.EmployeeCount"] = "{0} موظف",
            ["OrgStructure.DirectReports"] = "({0} تقرير مباشر)",
            // Adjustments (Bonuses/Penalties/Incentives) screen
            ["Adjustments.Title"] = "المكافآت والجزاءات والحوافز",
            ["Adjustments.Field.Month"] = "الشهر:",
            ["Adjustments.Col.Code"] = "الكود",
            ["Adjustments.Col.Employee"] = "الموظف",
            ["Adjustments.Col.Type"] = "النوع",
            ["Adjustments.Col.Amount"] = "المبلغ",
            ["Adjustments.Col.Description"] = "الوصف",
            ["Adjustments.Col.Created"] = "تاريخ الإنشاء",
            ["Adjustments.Field.Employee"] = "الموظف",
            ["Adjustments.Field.Type"] = "النوع",
            ["Adjustments.Field.Amount"] = "المبلغ",
            ["Adjustments.Field.Description"] = "الوصف",
            ["Adjustments.Note"] = "تُضاف المكافأة/الحافز إلى بدلات هذا الشهر؛ ويُضاف الجزاء إلى الخصومات — تلقائيًا، في المرة القادمة التي يتم فيها توليد رواتب هذا الشهر.",
            ["Adjustments.Button.Add"] = "إضافة",
            ["Adjustments.Button.Delete"] = "حذف المحدد",
            ["Adjustments.type.Bonus"] = "مكافأة",
            ["Adjustments.type.Incentive"] = "حافز",
            ["Adjustments.type.Penalty"] = "جزاء",

            // Common (shared across dialogs)
            ["Common.Ok"] = "موافق",
            ["Common.Cancel"] = "إلغاء",
            ["Common.Info"] = "معلومة",

            // Documents screen (general library — Important/Free/Other, not tied to an employee)
            ["Documents.Title"] = "المستندات",
            ["Documents.Button.Import"] = "استيراد...",
            ["Documents.Field.IconSize"] = "حجم الأيقونة:",
            ["Documents.Filter.All"] = "الكل",
            ["Documents.Category.Important"] = "مستندات هامة",
            ["Documents.Category.Free"] = "مستندات مجانية",
            ["Documents.Category.Other"] = "أخرى",
            ["Documents.NoDocuments"] = "لا توجد مستندات في هذا التصنيف بعد.",
            ["Documents.Sort.Button"] = "⇅ ترتيب",
            ["Documents.Sort.NameAsc"] = "الاسم (أ ← ي)",
            ["Documents.Sort.NameDesc"] = "الاسم (ي ← أ)",
            ["Documents.Sort.DateNewest"] = "التاريخ (الأحدث أولاً)",
            ["Documents.Sort.DateOldest"] = "التاريخ (الأقدم أولاً)",
            ["Documents.Sort.SizeLargest"] = "الحجم (الأكبر أولاً)",
            ["Documents.Sort.SizeSmallest"] = "الحجم (الأصغر أولاً)",
            ["Documents.Sort.Type"] = "نوع الملف",
            ["Documents.Button.Open"] = "فتح",
            ["Documents.Button.Print"] = "طباعة",
            ["Documents.Button.Rename"] = "إعادة تسمية",
            ["Documents.Button.Delete"] = "حذف",
            ["Documents.Field.Name"] = "اسم الملف",
            ["Documents.Field.Category"] = "التصنيف",
            ["Documents.Dialog.SelectFileTitle"] = "اختر ملفًا للاستيراد",
            ["Documents.Dialog.Filter.AllFiles"] = "جميع الملفات (*.*)|*.*",
            ["Documents.Dialog.ImportTitle"] = "استيراد مستند",
            ["Documents.Dialog.RenameTitle"] = "إعادة تسمية المستند",
            ["Documents.Validation.NameRequired"] = "لا يمكن أن يكون اسم الملف فارغًا.",
            ["Documents.Confirm.Delete"] = "حذف '{0}'؟ سيؤدي هذا أيضًا إلى إزالة النسخة المخزنة من القرص.",
            ["Documents.Error.LoadFailed"] = "تعذّر تحميل المستندات: {0}",
            ["Documents.Error.ImportFailed"] = "فشل الاستيراد: {0}",
            ["Documents.Error.OpenFailed"] = "تعذّر فتح الملف: {0}",
            ["Documents.Error.PrintFailed"] = "تعذّرت طباعة الملف: {0}",
            ["Documents.Error.RenameFailed"] = "فشلت إعادة التسمية: {0}",
            ["Documents.Error.DeleteFailed"] = "فشل الحذف: {0}",
            ["Documents.Error.FileMissing"] = "تعذّر العثور على هذا الملف على القرص (ربما تم نقله أو حذفه).",

            // Employment history event types (EmploymentHistoryEntry.EventTypeDefinitions) —
            // canonical values stay in EmploymentHistoryEntry.EventTypeDefinitions; these are
            // display-only translations, looked up by key, never stored.
            ["HistoryEventType.Hire"] = "تعيين",
            ["HistoryEventType.Promotion"] = "ترقية",
            ["HistoryEventType.DepartmentTransfer"] = "نقل قسم",
            ["HistoryEventType.PositionChange"] = "تغيير المسمى الوظيفي",
            ["HistoryEventType.SalaryChange"] = "تعديل راتب",
            ["HistoryEventType.PerformanceReview"] = "تقييم الأداء",
            ["HistoryEventType.Termination"] = "إنهاء الخدمة",
            ["HistoryEventType.Rehire"] = "إعادة تعيين",
            ["HistoryEventType.Other"] = "أخرى",

            // Employee document categories (EmployeeDocument.CategoryDefinitions) — canonical
            // values stay in EmployeeDocument.CategoryDefinitions (and the database's
            // CK_EmployeeDocuments_type constraint); these are display-only translations.
            ["EmployeeDocCategory.NationalId"] = "بطاقة الرقم القومي",
            ["EmployeeDocCategory.BirthCertificate"] = "شهادة الميلاد",
            ["EmployeeDocCategory.PersonalPhoto"] = "صورة شخصية",
            ["EmployeeDocCategory.GraduationCertificate"] = "شهادة التخرج",
            ["EmployeeDocCategory.CriminalRecord"] = "صحيفة الحالة الجنائية (فيش)",
            ["EmployeeDocCategory.MilitaryStatus"] = "شهادة الموقف التجنيدي",
            ["EmployeeDocCategory.LaborOfficeCard"] = "كعب عمل (مكتب العمل)",
            ["EmployeeDocCategory.SocialInsurance"] = "برنت تأمينات",
            ["EmployeeDocCategory.MedicalFitness"] = "شهادة لياقة طبية",
            ["EmployeeDocCategory.Contract"] = "عقد عمل",
            ["EmployeeDocCategory.Other"] = "أخرى",

        };
    }
}
